/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppNavbar: typeof import('./src/components/AppNavbar.vue')['default']
    BaseButton: typeof import('./src/components/base/BaseButton.vue')['default']
    BaseCard: typeof import('./src/components/base/BaseCard.vue')['default']
    BaseCheckbox: typeof import('./src/components/base/BaseCheckbox.vue')['default']
    BaseContainer: typeof import('./src/components/base/BaseContainer.vue')['default']
    BaseForm: typeof import('./src/components/base/BaseForm.vue')['default']
    BaseIcon: typeof import('./src/components/base/BaseIcon.vue')['default']
    BaseImage: typeof import('./src/components/base/BaseImage.vue')['default']
    BaseImageCard: typeof import('./src/components/base/BaseImageCard.vue')['default']
    BaseInput: typeof import('./src/components/base/BaseInput.vue')['default']
    BaseRating: typeof import('./src/components/base/BaseRating.vue')['default']
    CafeCard: typeof import('./src/components/CafeCard.vue')['default']
    CafeImage: typeof import('./src/components/CafeImage.vue')['default']
    EditCafeModal: typeof import('./src/components/EditCafeModal.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
